#!/bin/sh

ACTIVE_WINDOW_CLASS=$(hyprctl activewindow -j | jq .initialClass)
if [ "$ACTIVE_WINDOW_CLASS" = "\"kitty\"" ]; then
    ACTIVE_WINDOW_PID=$(hyprctl activewindow -j | jq .pid)
    CHILD_PID=$(pgrep -P "$ACTIVE_WINDOW_PID")
    if [ "$CHILD_PID" = "" ]; then
        kitty
    fi

    CHILD_CWD=$(pwdx "$CHILD_PID" | cut -d' ' -f2)
    kitty --directory "$CHILD_CWD"
else
    kitty
fi
